"""
fcm_notifier.py
───────────────
Sends personalised Firebase Cloud Messaging (FCM) push notifications
to every registered guest in an affected zone when an incident occurs.

Each guest gets their OWN notification:
  - A* path computed from THEIR room coordinates to the nearest unblocked exit
  - Turn-by-turn directions generated by direction_generator.py
  - Severity-appropriate colour / title
  - Full data payload so the guest PWA can render the map overlay

Zone targeting:
  Zone 1 → same floor  (immediate evacuation required)
  Zone 2 → adjacent floors in same block  (standby + be ready)
  Zone 3 → other blocks same level  (advisory only)
"""

import asyncio
from typing import List, Dict, Tuple
from firebase_admin import messaging

from app.db.collections import (
    get_room_occupants_on_floor,
    get_room_occupants_on_adj_floors,
    get_floor,
    get_exits_on_floor,
    get_pois_on_floor,
)
from app.services.pathfinding import astar
from app.services.direction_generator import generate_directions, format_distance


_ZONE1_TITLE = "🚨 EMERGENCY — Evacuate Now"
_ZONE2_TITLE = "⚠️ ALERT — Prepare to Evacuate"
_ZONE3_TITLE = "ℹ️ ADVISORY — Incident Nearby"

_SEVERITY_COLOR = {
    "CRITICAL": "#dc2626",
    "HIGH":     "#ea580c",
    "MEDIUM":   "#d97706",
    "LOW":      "#16a34a",
}


def _nearest_unblocked_exit(
    exits: List[Dict],
    guest_x: int, guest_y: int,
    blocked_set: set,
) -> Dict | None:
    """Find the closest safe exit that is not itself a blocked node."""
    valid = [
        e for e in exits
        if (e["coord_x"], e["coord_y"]) not in blocked_set
    ]
    if not valid:
        valid = exits  # all blocked — edge case, use any exit
    return min(valid, key=lambda e: abs(e["coord_x"] - guest_x) + abs(e["coord_y"] - guest_y))


async def _send_one(
    token: str,
    title: str,
    body: str,
    data: Dict[str, str],
) -> None:
    """Fire-and-forget single FCM message. Failures are logged, not raised."""
    try:
        msg = messaging.Message(
            notification=messaging.Notification(title=title, body=body),
            data=data,
            token=token,
            android=messaging.AndroidConfig(priority="high"),
            apns=messaging.APNSConfig(
                headers={"apns-priority": "10"},
                payload=messaging.APNSPayload(
                    aps=messaging.Aps(sound="emergency.aiff", badge=1)
                ),
            ),
        )
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, lambda: messaging.send(msg))
    except Exception as e:
        print(f"[ARIA-FCM] Failed to send to token ...{token[-6:]}: {e}")


async def send_zone_evacuation_notifications(
    incident_type: str,
    severity: str,
    full_location: str,
    floor_id: str,
    floor_level: int,
    block_id: str,
    block_code: str,
    blocked_nodes: List[List[int]],
    incident_id: str,
) -> None:
    """
    Main entry point called from zone_resolver_node after an incident is persisted.

    For zone 1 (same floor):  compute personalised A* per room, send immediate evac
    For zone 2 (adj floors):  generic standby notification
    For zone 3:                skipped (advisory only — handled by staff dashboard)
    """
    blocked_set: set[Tuple[int, int]] = {(b[0], b[1]) for b in blocked_nodes}

    # ── Load floor data once ─────────────────────────────────────
    floor = await get_floor(floor_id)
    if not floor:
        print(f"[ARIA-FCM] Floor {floor_id} not found — skipping notifications")
        return

    grid   = floor["static_grid"]
    exits  = await get_exits_on_floor(floor_id)
    pois   = await get_pois_on_floor(floor_id)
    if not exits:
        print("[ARIA-FCM] No exits on floor — skipping notifications")
        return

    # ── ZONE 1: same floor personalized notifications ─────────────
    zone1_rooms = await get_room_occupants_on_floor(floor_id)

    tasks = []
    for room_doc in zone1_rooms:
        guest_x = room_doc["coord_x"]
        guest_y = room_doc["coord_y"]
        origin  = room_doc["room_name"]

        exit_poi = _nearest_unblocked_exit(exits, guest_x, guest_y, blocked_set)
        path = astar(
            grid    = grid,
            start   = (guest_x, guest_y),
            end     = (exit_poi["coord_x"], exit_poi["coord_y"]),
            blocked = [tuple(b) for b in blocked_nodes],
        )

        steps    = generate_directions(path, pois, exit_poi["name"], origin)
        distance = format_distance(path)
        body = f"Head to {exit_poi['name']} ({distance}). {steps[0] if steps else ''}"

        # Data payload for PWA map overlay
        data_payload = {
            "incident_id":   incident_id,
            "incident_type": incident_type,
            "severity":      severity,
            "exit_name":     exit_poi["name"],
            "exit_coord":    f"{exit_poi['coord_x']},{exit_poi['coord_y']}",
            "distance":      distance,
            "path":          ";".join(f"{c[0]},{c[1]}" for c in path),
            "blocked":       ";".join(f"{b[0]},{b[1]}" for b in blocked_nodes),
            "steps":         "||".join(steps),
            "full_location": full_location,
            "zone":          "1",
            "color":         _SEVERITY_COLOR.get(severity, "#dc2626"),
        }

        for occupant in room_doc.get("occupants", []):
            token = occupant.get("fcm_token")
            if token:
                tasks.append(_send_one(
                    token  = token,
                    title  = _ZONE1_TITLE,
                    body   = body,
                    data   = data_payload,
                ))

    # ── ZONE 2: adjacent floors — standy notification ─────────────
    adj_levels = [floor_level - 1, floor_level + 1]
    zone2_rooms = await get_room_occupants_on_adj_floors(block_id, adj_levels)

    for room_doc in zone2_rooms:
        body_z2 = (
            f"Incident on Floor {floor_level}, Block {block_code}. "
            f"Be ready to evacuate on instruction."
        )
        data_z2 = {
            "incident_id":   incident_id,
            "incident_type": incident_type,
            "severity":      severity,
            "full_location": full_location,
            "zone":          "2",
            "color":         _SEVERITY_COLOR.get(severity, "#ea580c"),
        }
        for occupant in room_doc.get("occupants", []):
            token = occupant.get("fcm_token")
            if token:
                tasks.append(_send_one(
                    token  = token,
                    title  = _ZONE2_TITLE,
                    body   = body_z2,
                    data   = data_z2,
                ))

    # ── Fire all notifications concurrently ───────────────────────
    if tasks:
        await asyncio.gather(*tasks, return_exceptions=True)
        print(f"[ARIA-FCM] Sent {len(tasks)} notifications for incident {incident_id}")
    else:
        print("[ARIA-FCM] No FCM tokens registered — no push notifications sent")
